#!/usr/bin/env swift

import Foundation

let scriptDirectory = (#filePath as NSString).deletingLastPathComponent
let repositoryPath = (scriptDirectory as NSString).deletingLastPathComponent
let resourcesPath = (repositoryPath as NSString).appendingPathComponent("Sources/linkly/Resources")
let outputPath = (repositoryPath as NSString)
    .appendingPathComponent("Sources/linkly/Generated/EmbeddedResources.swift")
let fileManager = FileManager.default

struct ResourceFile {
    let name: String
    let path: String
}

func resourceFiles(in directory: String, extension fileExtension: String) throws -> [ResourceFile] {
    try fileManager.contentsOfDirectory(atPath: directory)
        .filter { ($0 as NSString).pathExtension.lowercased() == fileExtension }
        .sorted()
        .map { ResourceFile(name: $0, path: (directory as NSString).appendingPathComponent($0)) }
}

func swiftStringLiteral(_ value: String) -> String {
    "\"" + value
        .replacingOccurrences(of: "\\", with: "\\\\")
        .replacingOccurrences(of: "\"", with: "\\\"") + "\""
}

func encodedExpression(for data: Data, indentation: String) -> String {
    let encoded = data.base64EncodedString()
    let chunks = stride(from: 0, to: encoded.count, by: 100).map { offset -> String in
        let start = encoded.index(encoded.startIndex, offsetBy: offset)
        let end = encoded.index(start, offsetBy: min(100, encoded.count - offset))
        return indentation + swiftStringLiteral(String(encoded[start..<end]))
    }
    return chunks.joined(separator: " +\n")
}

func dictionarySource(files: [ResourceFile], key: (ResourceFile) -> String) throws -> String {
    var entries: [String] = []
    for file in files {
        let data = try Data(contentsOf: URL(fileURLWithPath: file.path))
        let encoded = encodedExpression(for: data, indentation: "                ")
        entries.append(
            "        \(swiftStringLiteral(key(file))): decode(\n" +
            encoded + "\n" +
            "        )"
        )
    }
    return entries.joined(separator: ",\n")
}

let iconFiles = try resourceFiles(
    in: (resourcesPath as NSString).appendingPathComponent("Icons"),
    extension: "svg"
)
let templateFiles = try resourceFiles(
    in: (resourcesPath as NSString).appendingPathComponent("Templates"),
    extension: "leaf"
)

let icons = try dictionarySource(files: iconFiles) {
    ($0.name as NSString).deletingPathExtension.lowercased()
}
let templates = try dictionarySource(files: templateFiles) {
    $0.name
}

let generated = """
// This file is generated by Scripts/generate-embedded-resources.swift.
// Do not edit it directly.

import Foundation

enum EmbeddedResources {
    static let icons: [String: String] = [
\(icons)
    ]

    static let templates: [String: String] = [
\(templates)
    ]

    private static func decode(_ encoded: String) -> String {
        guard let data = Data(base64Encoded: encoded),
              let value = String(data: data, encoding: .utf8)
        else {
            preconditionFailure("Invalid generated embedded resource")
        }
        return value
    }
}
"""

let outputDirectory = (outputPath as NSString).deletingLastPathComponent
try fileManager.createDirectory(atPath: outputDirectory, withIntermediateDirectories: true)
try generated.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("Generated \(outputPath) with \(iconFiles.count) icons and \(templateFiles.count) templates")
